import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('titanic.csv')  
print("🔹 First 5 Rows of the Dataset:")
print(df.head())
print("\n🔹 Dataset Info:")
print(df.info())
print("\n🔹 Missing Values:")
print(df.isnull().sum())
print("\n🔹 Statistical Summary:")
print(df.describe())
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
plt.figure(figsize=(10, 5))
sns.histplot(df['Age'], kde=True, bins=30)
plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()
sns.countplot(x='Survived', data=df)
plt.title("Survival Count (0 = Not Survived, 1 = Survived)")
plt.show()
plt.figure(figsize=(8, 6))
sns.boxplot(x='Pclass', y='Age', data=df)
plt.title("Passenger Class vs Age")
plt.show()
plt.figure(figsize=(10, 8))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
print("\n🔹 Survival Rate by Passenger Class:")
print(df.groupby('Pclass')['Survived'].mean())
print("\n🔹 Survival Rate by Gender:")
print(df.groupby('Sex')['Survived'].mean())
